import {
  Search,
  Cpu,
  Sparkles,
  Megaphone,
  Code2,
  ListChecks,
  User,
  Palette,
  Share2,
  PenLine,
  Target,
  Scale,
  Gamepad2,
  GraduationCap,
  Heart,
  ShoppingCart,
  Compass,
  Briefcase,
  Mic,
  Bitcoin,
  Handshake,
  ShieldCheck,
  MapPin,
  Newspaper,
  Globe,
  Trophy,
  Home,
  Shapes,
  type LucideIcon,
} from "lucide-react";

// Ordered by specificity — first keyword match wins, so put narrower
// terms before broad ones if you add more.
const KEYWORD_ICONS: [string, LucideIcon][] = [
  ["seo", Search],
  ["ai agent", Cpu],
  ["infrastructure", Cpu],
  ["media generation", Sparkles],
  ["marketing", Megaphone],
  ["advertising", Megaphone],
  ["developer", Code2],
  ["productivity", ListChecks],
  ["people", User],
  ["profile", User],
  ["design", Palette],
  ["creative", Palette],
  ["social", Share2],
  ["writing", PenLine],
  ["content", PenLine],
  ["sales", Target],
  ["lead", Target],
  ["business", Scale],
  ["finance", Scale],
  ["legal", Scale],
  ["game", Gamepad2],
  ["entertainment", Gamepad2],
  ["education", GraduationCap],
  ["learning", GraduationCap],
  ["health", Heart],
  ["fitness", Heart],
  ["wellness", Heart],
  ["ecommerce", ShoppingCart],
  ["retail", ShoppingCart],
  ["directory", Compass],
  ["discovery", Compass],
  ["hiring", Briefcase],
  ["job", Briefcase],
  ["career", Briefcase],
  ["audio", Mic],
  ["voice", Mic],
  ["podcast", Mic],
  ["crypto", Bitcoin],
  ["web3", Bitcoin],
  ["invest", Bitcoin],
  ["agenc", Handshake],
  ["studio", Handshake],
  ["service", Handshake],
  ["security", ShieldCheck],
  ["privacy", ShieldCheck],
  ["compliance", ShieldCheck],
  ["travel", MapPin],
  ["local", MapPin],
  ["lifestyle", MapPin],
  ["media", Newspaper],
  ["news", Newspaper],
  ["domain", Globe],
  ["web asset", Globe],
  ["leaderboard", Trophy],
  ["attention market", Trophy],
  ["real estate", Home],
  ["property", Home],
];

export function getCategoryIcon(name: string): LucideIcon {
  const lower = name.toLowerCase();
  const match = KEYWORD_ICONS.find(([keyword]) => lower.includes(keyword));
  return match?.[1] ?? Shapes;
}
